# -*- coding: utf-8 -*-
"""appcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeu-NdfwnZt2VpvuqiAIZUtQ9-an_-g0
"""

pip install streamlit

import streamlit as st
import tensorflow as tf
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Load the trained model
model_path='/content/drive/MyDrive/Dataset/energy_saving_model.h5'
model = tf.keras.models.load_model(model_path, custom_objects={'mse': tf.keras.losses.mse})
scaler_path='/content/drive/MyDrive/Dataset/scaler.pkl'
scaler = joblib.load(scaler_path)  # Load the scaler used for normalization

# Function to predict energy consumption
def predict_energy(input_data):
    input_array = np.array(input_data).reshape(1, -1)
    input_array = scaler.transform(input_array)  # Normalize input
    prediction = model.predict(input_array)
    return prediction[0][0]

# Streamlit UI
st.title("Energy Consumption Prediction App")
st.write("Enter the following details to predict energy consumption:")

temperature = st.number_input("Temperature (°C)", value=25)
humidity = st.number_input("Humidity (%)", value=50)
square_footage = st.number_input("Square Footage", value=1500)
occupancy = st.number_input("Occupancy (people)", value=3)
hvac_usage = st.radio("HVAC Usage", ["On", "Off"])
lighting_usage = st.radio("Lighting Usage", ["On", "Off"])
renewable_energy = st.number_input("Renewable Energy Generated (kWh)", value=5.0)
holiday = st.number_input("Holiday (0 = No, 1 = Yes)", value=0)
energyconsumption = st.number_input("Previous Energy Consumption (kWh)", value=50)


hvac_usage = 1 if hvac_usage == "On" else 0
lighting_usage = 1 if lighting_usage == "On" else 0

input_data = [temperature, humidity, square_footage, occupancy, hvac_usage, lighting_usage, renewable_energy, holiday, energyconsumption]
prediction = predict_energy(input_data)

st.success(f"Predicted Energy Consumption: {prediction:.2f} kWh")

# Instructions to Run in Colab
st.write("### How to Run this App in Google Colab")
st.code("""
!pip install streamlit
!streamlit run energy_app.py
""", language="bash")

from google.colab import drive
drive.mount('/content/drive')